package snake;

import javax.swing.JOptionPane;

/**
 * GameOver.java - GameOVer Menu
 *
 * @teacher Mr.Wachs
 * @author Raden Pablo
 * @since Jan. 9, 2020,10:36:42 a.m.
 */
public class GameOver extends javax.swing.JFrame {

    private GamePlay play;

    private final int FORM_WIDTH = 582;
    private final int FORM_HEIGHT = 467;

    /**
     * Creates new form GameOverMenu
     *
     * @param play
     */
    public GameOver(GamePlay play) {
        this.play = play;
        initComponents();
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlayQuestion = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        btnYes = new javax.swing.JButton();
        lblgameover = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblPlayQuestion.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        lblPlayQuestion.setText("Do you want to Play Again?");
        getContentPane().add(lblPlayQuestion);
        lblPlayQuestion.setBounds(130, 350, 270, 30);

        btnNo.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnNo.setText("No");
        btnNo.setBorderPainted(false);
        btnNo.setContentAreaFilled(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo);
        btnNo.setBounds(290, 390, 110, 60);

        btnYes.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        btnYes.setText("Yes");
        btnYes.setBorderPainted(false);
        btnYes.setContentAreaFilled(false);
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(150, 400, 110, 50);

        lblgameover.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        lblgameover.setText("Game Over");
        getContentPane().add(lblgameover);
        lblgameover.setBounds(140, 20, 330, 80);

        lblScore.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        lblScore.setText("Points:");
        getContentPane().add(lblScore);
        lblScore.setBounds(180, 320, 70, 20);

        lblPoints.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        lblPoints.setText("0");
        getContentPane().add(lblPoints);
        lblPoints.setBounds(260, 320, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/dizzy.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 100, 180, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/white.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        JOptionPane.showMessageDialog(null, "Thanks for Playing");
        System.exit(0);
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        new GamePlay();
        this.dispose();
    }//GEN-LAST:event_btnYesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPlayQuestion;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblgameover;
    // End of variables declaration//GEN-END:variables

    /**
     * sets the form
     */
    private void setForm() {
        this.setSize(FORM_WIDTH, FORM_HEIGHT);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        System.out.println(play.points);
        lblPoints.setText("" + play.points);
    }
}
