/*
 *  required package class namespace 

 */
package snake;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import media.MediaPlayer;

/**
 * GameMenu.java - Menu of the Game
 *
 * @teacher Mr.Wachs
 * @author Raden Pablo
 * @since Jan. 9, 2020,10:36:42 a.m.
 */
public class GameMenu extends javax.swing.JFrame {

    //Global Variables
    private final int FORM_WIDTH = 792;
    private final int FORM_HEIGHT = 560;

    private Timer musicCheck;

    /**
     * Creates new form GameMenu
     */
    public GameMenu() {
        initComponents();
        MediaPlayer music = new MediaPlayer();
        music.playWAV("snakeMusic.wav");
        
        // loop the music
        musicCheck = new Timer(1, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (music.isRunning() == false) {
                    music.playWAV("Monopoly Deluxe - Music 1.wav");
                }
            }
        });
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRules = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblText.setFont(new java.awt.Font("Algerian", 0, 100)); // NOI18N
        lblText.setText("HIssss.io");
        getContentPane().add(lblText);
        lblText.setBounds(60, 180, 570, 110);

        btnPlay.setBackground(new java.awt.Color(139, 220, 164));
        btnPlay.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(80, 470, 130, 50);

        btnExit.setBackground(new java.awt.Color(139, 220, 164));
        btnExit.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        btnExit.setText("EXit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(560, 470, 130, 50);

        btnRules.setBackground(new java.awt.Color(139, 220, 164));
        btnRules.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        btnRules.setText("Rules");
        btnRules.setBorderPainted(false);
        btnRules.setContentAreaFilled(false);
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRules);
        btnRules.setBounds(290, 470, 160, 50);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Snake.gif"))); // NOI18N
        getContentPane().add(lblBack);
        lblBack.setBounds(0, 0, 800, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        new Rules();
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnRulesActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        new GamePlay();
        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRules;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        this.setSize(FORM_WIDTH, FORM_HEIGHT);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
    }

}
