/*
 *  required package class namespace 

 */
package snake;

/**
 * Rules.java - Display Rule
 *
 * @teacher Mr.Wachs
 * @author Raden Pablo
 * @since Dec. 11, 2019,10:13:42 a.m.
 */
public class Rules extends javax.swing.JFrame {

    //Global Variables
    private final int FORM_WIDTH = 537;
    private final int FORM_HEIGHT = 519;

    /**
     * Creates new form Rules
     */
    public Rules() {
        initComponents();
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWords = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblRule2part2 = new javax.swing.JLabel();
        lblPic5 = new javax.swing.JLabel();
        lblRules1 = new javax.swing.JLabel();
        lblRules2 = new javax.swing.JLabel();
        lblRule3 = new javax.swing.JLabel();
        lblRule3part2 = new javax.swing.JLabel();
        lblRule3part3 = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblPic2 = new javax.swing.JLabel();
        lblPic3 = new javax.swing.JLabel();
        lblPic4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblWords.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        lblWords.setText("Rules");
        getContentPane().add(lblWords);
        lblWords.setBounds(190, 50, 160, 130);

        btnBack.setBackground(new java.awt.Color(0, 255, 0));
        btnBack.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        btnBack.setText("Go Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 10, 150, 50);

        lblRule2part2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRule2part2.setText(" save at the leaderBoard");
        getContentPane().add(lblRule2part2);
        lblRule2part2.setBounds(30, 230, 460, 33);

        lblPic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Snake.png"))); // NOI18N
        lblPic5.setText("jLabel1");
        getContentPane().add(lblPic5);
        lblPic5.setBounds(340, 320, 200, 200);

        lblRules1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRules1.setText("2. aS YOU GROW YOU GAIN POINTS  Which will");
        getContentPane().add(lblRules1);
        lblRules1.setBounds(10, 190, 580, 40);

        lblRules2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRules2.setText("1. When you eat an apple you grow longer");
        getContentPane().add(lblRules2);
        lblRules2.setBounds(10, 150, 580, 40);

        lblRule3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRule3.setText("3. There is a total of two power up. ");
        getContentPane().add(lblRule3);
        lblRule3.setBounds(10, 260, 570, 33);

        lblRule3part2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRule3part2.setText("generates more apples.");
        getContentPane().add(lblRule3part2);
        lblRule3part2.setBounds(40, 320, 450, 33);

        lblRule3part3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblRule3part3.setText("One gives you  Speed and the other");
        getContentPane().add(lblRule3part3);
        lblRule3part3.setBounds(40, 290, 450, 33);

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Background.jpg"))); // NOI18N
        getContentPane().add(lblPic);
        lblPic.setBounds(80, -210, 490, 770);

        lblPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Background.jpg"))); // NOI18N
        getContentPane().add(lblPic2);
        lblPic2.setBounds(0, -210, 490, 770);

        lblPic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Background.jpg"))); // NOI18N
        getContentPane().add(lblPic3);
        lblPic3.setBounds(0, -30, 490, 770);

        lblPic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Background.jpg"))); // NOI18N
        getContentPane().add(lblPic4);
        lblPic4.setBounds(90, -20, 490, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        GameMenu gamemenu = new GameMenu();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPic2;
    private javax.swing.JLabel lblPic3;
    private javax.swing.JLabel lblPic4;
    private javax.swing.JLabel lblPic5;
    private javax.swing.JLabel lblRule2part2;
    private javax.swing.JLabel lblRule3;
    private javax.swing.JLabel lblRule3part2;
    private javax.swing.JLabel lblRule3part3;
    private javax.swing.JLabel lblRules1;
    private javax.swing.JLabel lblRules2;
    private javax.swing.JLabel lblWords;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        this.setSize(FORM_WIDTH, FORM_HEIGHT);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);

    }
}
